#!/usr/bin/env python3
"""Generate Chapter 12 lessons and static HTML exports from lab notebooks."""

from __future__ import annotations

import sys
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable
from urllib.parse import quote

try:
    import nbformat
    from nbconvert import HTMLExporter
except ImportError as exc:  # pragma: no cover - exercised by runtime environment
    raise SystemExit(
        "Missing notebook export dependencies. Install them with "
        "`pip install nbconvert nbformat` or the repo setup command in AGENTS.md."
    ) from exc


ROOT_DIR = Path(__file__).resolve().parents[1]
LABS_DIR = ROOT_DIR / "labs"
SOLUTIONS_DIR = LABS_DIR / "solutions"
GENERATED_HTML_DIR = ROOT_DIR / "public" / "generated" / "labs"
GENERATED_POSTS_DIR = ROOT_DIR / "contents" / "vi" / "chapter12" / "_posts"
POST_DATE = "2026-03-14"
AUTO_GENERATED_HTML = (
    "<!-- AUTO-GENERATED by scripts/generate_lab_chapter.py. DO NOT EDIT. -->\n"
)
AUTO_GENERATED_MD = "<!-- AUTO-GENERATED. DO NOT EDIT MANUALLY. -->"
LAB_FILENAME_RE = re.compile(r"Bayesian Inference - Lab (\d+)\.ipynb$")
SOLUTION_FILENAME_RE = re.compile(r"Lab_(\d+)_Solutions\.ipynb$")


@dataclass(frozen=True)
class LabPair:
    """Notebook pair used to generate one Chapter 12 lesson."""

    number: int
    lab_path: Path
    solution_path: Path

    @property
    def lesson_title(self) -> str:
        return f"Bài 12.{self.number}: Lab {self.number}"

    @property
    def lesson_filename(self) -> str:
        return f"{POST_DATE}-12_{self.number:02d}_lab_{self.number:02d}.md"

    @property
    def lesson_permalink(self) -> str:
        return f"/vi/chapter12/lab-{self.number:02d}/"

    @property
    def lab_html_name(self) -> str:
        return f"lab-{self.number:02d}.html"

    @property
    def solution_html_name(self) -> str:
        return f"lab-{self.number:02d}-solution.html"


def discover_lab_pairs() -> list[LabPair]:
    """Match notebook prompts and solutions by lab number."""

    lab_map: dict[int, Path] = {}
    for notebook_path in sorted(LABS_DIR.glob("*.ipynb")):
        match = LAB_FILENAME_RE.fullmatch(notebook_path.name)
        if match:
            lab_map[int(match.group(1))] = notebook_path

    solution_map: dict[int, Path] = {}
    for notebook_path in sorted(SOLUTIONS_DIR.glob("Lab_*_Solutions.ipynb")):
        match = SOLUTION_FILENAME_RE.fullmatch(notebook_path.name)
        if match:
            solution_map[int(match.group(1))] = notebook_path

    if not lab_map:
        raise SystemExit(f"No lab notebooks found in {LABS_DIR}")

    mismatches: list[str] = []
    all_numbers = sorted(set(lab_map) | set(solution_map))
    for number in all_numbers:
        if number not in lab_map:
            mismatches.append(f"Missing prompt notebook for Lab {number}")
        if number not in solution_map:
            mismatches.append(f"Missing solution notebook for Lab {number}")

    if mismatches:
        mismatch_text = "\n".join(f"- {item}" for item in mismatches)
        raise SystemExit(f"Notebook pairs are incomplete:\n{mismatch_text}")

    return [
        LabPair(number=number, lab_path=lab_map[number], solution_path=solution_map[number])
        for number in sorted(all_numbers)
    ]


def reset_generated_outputs() -> None:
    """Remove stale generated files so reruns stay clean."""

    if GENERATED_HTML_DIR.exists():
        shutil.rmtree(GENERATED_HTML_DIR)
    GENERATED_HTML_DIR.mkdir(parents=True, exist_ok=True)

    GENERATED_POSTS_DIR.mkdir(parents=True, exist_ok=True)
    for markdown_path in GENERATED_POSTS_DIR.glob("*.md"):
        markdown_path.unlink()


def build_exporter() -> HTMLExporter:
    """Configure a stable notebook exporter."""

    exporter = HTMLExporter(template_name="classic")
    exporter.exclude_input_prompt = True
    exporter.exclude_output_prompt = True
    if hasattr(exporter, "embed_images"):
        exporter.embed_images = True
    return exporter


def export_notebook_html(notebook_path: Path, output_path: Path, exporter: HTMLExporter) -> None:
    """Render one notebook into a standalone HTML file."""

    notebook_node = nbformat.read(notebook_path, as_version=4)
    html_body, resources = exporter.from_notebook_node(notebook_node)
    output_path.write_text(AUTO_GENERATED_HTML + html_body, encoding="utf-8")

    for asset_name, asset_content in resources.get("outputs", {}).items():
        asset_path = output_path.parent / asset_name
        asset_path.parent.mkdir(parents=True, exist_ok=True)
        if isinstance(asset_content, str):
            asset_path.write_text(asset_content, encoding="utf-8")
        else:
            asset_path.write_bytes(asset_content)


def encode_site_path(path: Path) -> str:
    """Convert a repository path into a URL-safe site path."""

    relative_path = path.relative_to(ROOT_DIR).as_posix()
    return "/" + quote(relative_path, safe="/")


def generated_site_path(*parts: str) -> str:
    """Build a site-relative path inside public/generated/labs."""

    return "/" + "/".join(["public", "generated", "labs", *parts])


def render_resource_links(html_path: str, notebook_path: str, label: str) -> str:
    """Render the standard link group used above each notebook iframe."""

    return f"""<div class="lab-resource-links">
  <a href="{{{{ '{html_path}' | relative_url }}}}" target="_blank" rel="noopener noreferrer">Mở {label} dạng HTML</a>
  <a href="{{{{ '{notebook_path}' | relative_url }}}}" target="_blank" rel="noopener noreferrer">Tải {label} .ipynb</a>
</div>"""


def render_lesson_markdown(pair: LabPair) -> str:
    """Render one generated Chapter 12 lesson."""

    prompt_html_path = generated_site_path(pair.lab_html_name)
    solution_html_path = generated_site_path(pair.solution_html_name)
    prompt_notebook_path = encode_site_path(pair.lab_path)
    solution_notebook_path = encode_site_path(pair.solution_path)

    return f"""---
layout: post
title: "{pair.lesson_title}"
chapter: '12'
order: {pair.number}
owner: Nguyen Le Linh
lang: vi
permalink: {pair.lesson_permalink}
categories:
- chapter12
lesson_type: required
---
{AUTO_GENERATED_MD}

<div class="lab-generation-note">
  Trang này được sinh tự động từ notebook trong <code>labs/</code> và <code>labs/solutions/</code>.
  Khi file notebook thay đổi, hãy chạy lại <code>python scripts/generate_lab_chapter.py</code> để cập nhật Chapter 12.
</div>

<div class="lab-section">
  <h2>Đề lab</h2>
  <p>Bạn có thể đọc trực tiếp notebook trên web, mở file HTML riêng, hoặc tải file <code>.ipynb</code> gốc để làm việc local.</p>
  {render_resource_links(prompt_html_path, prompt_notebook_path, f"Lab {pair.number}")}
  <iframe class="lab-notebook-frame" src="{{{{ '{prompt_html_path}' | relative_url }}}}" title="Lab {pair.number} notebook"></iframe>
</div>

<div class="lab-section">
  <h2>Solution</h2>
  <p>Phần solution được đặt cùng trang để đối chiếu workflow, lời giải và code sau khi bạn đã tự làm xong đề lab.</p>
  {render_resource_links(solution_html_path, solution_notebook_path, f"Solution Lab {pair.number}")}
  <iframe class="lab-notebook-frame" src="{{{{ '{solution_html_path}' | relative_url }}}}" title="Lab {pair.number} solution notebook"></iframe>
</div>
"""


def generate_outputs(pairs: Iterable[LabPair]) -> None:
    """Generate all static HTML files and Chapter 12 lessons."""

    exporter = build_exporter()

    for pair in pairs:
        export_notebook_html(pair.lab_path, GENERATED_HTML_DIR / pair.lab_html_name, exporter)
        export_notebook_html(
            pair.solution_path,
            GENERATED_HTML_DIR / pair.solution_html_name,
            exporter,
        )

        lesson_path = GENERATED_POSTS_DIR / pair.lesson_filename
        lesson_path.write_text(render_lesson_markdown(pair), encoding="utf-8")


def main() -> int:
    pairs = discover_lab_pairs()
    reset_generated_outputs()
    generate_outputs(pairs)

    print(f"Generated Chapter 12 from {len(pairs)} lab pairs.")
    print(f"- HTML exports: {GENERATED_HTML_DIR}")
    print(f"- Lesson pages: {GENERATED_POSTS_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
